# Generated by Django 5.1.6 on 2025-04-14 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Department Name')),
                ('address', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency_logos/')),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('managed_by', models.OneToOneField(limit_choices_to={'user_type': 'agency'}, on_delete=django.db.models.deletion.CASCADE, related_name='managing_agency', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
            },
        ),
    ]
