# Generated by Django 5.1.6 on 2025-04-14 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('receipt_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('user_address', models.TextField(verbose_name='Location Address of Complaint')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaint_images/', verbose_name='Image (Optional)')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('viewed', 'Viewed by Agency'), ('resolved', 'Resolved')], default='submitted', max_length=20)),
                ('agency_response', models.TextField(blank=True, null=True, verbose_name='Agency Response')),
                ('response_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tagged_agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tagged_complaints', to='agencies.agency', verbose_name='Concerned Agency Department')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
